#!/bin/bash

GIT_WORK_TREE=/home/{{ ansible_user }}/deploy/checkbox-stable-www git checkout -f

echo ""
echo "|||||||||||||||||||||||||||||||||||||||||"
echo "||||                                 ||||"
echo "||||    Pushed to checkbox-stable    ||||"
echo "||||                                 ||||"
echo "|||||||||||||||||||||||||||||||||||||||||"
echo ""

echo ""
echo "|||||||||||||||||||||||||||||||||||||||||||||||||||"
echo "||||                                           ||||"
echo "||||    Provisioning Checkbox-Stable server    ||||"
echo "||||                                           ||||"
echo "|||||||||||||||||||||||||||||||||||||||||||||||||||"
echo ""

sudo node /home/{{ ansible_user }}/JenkinsDeploy/provisioners/aws-checkbox-stable.js
sudo chown ubuntu /home/{{ ansible_user }}/JenkinsDeploy/checkbox-stable.key
sleep 10

echo ""
echo "||||||||||||||||||||||||||||||||||||||||||||||||||"
echo "||||                                          ||||"
echo "||||    Configuring Checkbox-Stable server    ||||"
echo "||||                                          ||||"
echo "||||||||||||||||||||||||||||||||||||||||||||||||||"
echo ""

sudo ansible-playbook /home/{{ ansible_user }}/JenkinsDeploy/playbooks/checkbox-stable.yml -i /home/{{ ansible_user }}/JenkinsDeploy/checkbox-stable-inventory
