#!/bin/bash

GIT_WORK_TREE=/home/{{ ansible_user }}/deploy/checkbox-stable-www git checkout -f

echo ""
echo "|||||||||||||||||||||||||||||||||||||||||"
echo "||||                                 ||||"
echo "||||    Pushed to checkbox-stable    ||||"
echo "||||                                 ||||"
echo "|||||||||||||||||||||||||||||||||||||||||"
echo ""

cd /home/ubuntu/JenkinsDeploy/

echo ""
echo "|||||||||||||||||||||||||||||||||||||||||||||||||||"
echo "||||                                           ||||"
echo "||||    Provisioning Checkbox-Stable server    ||||"
echo "||||                                           ||||"
echo "|||||||||||||||||||||||||||||||||||||||||||||||||||"
echo ""

sudo node provisioners/aws-checkbox-stable.js
sudo chown ubuntu /home/ubuntu/checkbox-stable.key

echo ""
echo "||||||||||||||||||||||||||||||||||||||||||||||||||"
echo "||||                                          ||||"
echo "||||    Configuring Checkbox-Stable server    ||||"
echo "||||                                          ||||"
echo "||||||||||||||||||||||||||||||||||||||||||||||||||"
echo ""

sudo ansible-playbook playbooks/checkbox-stable.yml -i checkbox-stable-inventory
